---
   
   - name: Update all packages to the latest version
     yum:
       name: yum-utils
       state: present
       update_cache: yes   
   - name: Add the HashiCorp GPG key | Verify the key's fingerprint  | Add the official HashiCorp Linux repository.
     shell: sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
   
   - name: Install vault
     yum:
       name: vault
       state: present
       update_cache: true

   - name: check for vault installation
     debug:
      msg: "vault successfully installed on Amazon linux distribution"     
