---
- name: Update the System Packages
  apt:
    upgrade: yes
    update_cache: yes
 
- name: Create a Tomcat Group
  group:
    name: tomcat
 
- name: Create a Tomcat user
  user:
    name: tomcat
 
- name: Install JAVA
  apt:
    name: default-jdk
    state: present
 
 
- name: Create a Tomcat Directory
  file:
    path: /opt/tomcat10
    owner: tomcat
    group: tomcat
    mode: 755
    recurse: yes
 
- name: download & unarchive tomcat10 
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.82/bin/apache-tomcat-8.5.82.tar.gz
    dest: /opt/tomcat10
    remote_src: yes
    #extra_opts: [--strip-components=1]
 
- name: Change ownership of tomcat directory
  file:
    path: /opt/tomcat10
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory
 
- name: Copy Tomcat service from local to remote
  copy:
    src: tomcat.service
    dest: /etc/systemd/system/
    mode: 0755
  notify: Restart tomcat

